### ISSUE TITLE
Handle named exports?

### ISSUE THREAD

**Issue by rwjblue** [alexspeller/ember-cli-coffees6#1]
Running `ember generate initializer foo` for example generates the following file:

```javascript
export function initialize(/* container, application */) {
  // application.inject('route', 'foo', 'service:foo');
};

export default {
  name: 'foo',
  initialize: initialize
};
```

**Comment by alexspeller** [comment]
@eventualbuddha that is amazing, thank you so much for that concise info. I will implement this ASAP (super busy until mid Jan but should have some time after that)

**Comment by alexspeller** [comment]
Finally this should be fixed now with version 0.2.0. I would massively appreciate a second set of eyes if anyone has a minute, just to look at [the tests](https://github.com/alexspeller/ember-cli-coffees6/blob/master/tests/filter-test.coffee) and check that the addon does what you would expect.

**Comment by eventualbuddha** [comment]
@alexspeller Looks right :+1:

**Comment by alexspeller** [comment]
Great, thanks!
