### ISSUE TITLE
Update ember-cli generators to generate coffeescript files without backticks

### ISSUE THREAD

**Issue by erichonkanen** [alexspeller/ember-cli-coffees6#13]
Hello,

I am using this library and while I can run e.g. `ember generate route myroute` and generate the route file as `myroute.coffee`, the actual contents include backticks.

It'd be nice if we could generate the coffeescript files without backticks (thats through ember-cli-coffeescript currently)

Any thoughts?

**Comment by alexspeller** [comment]
Yes, I would love for this to be the case. I'm not currently sure if I can override the definitions. In addition, I don't want to maintain a set of generators that mirror ember-cli-coffeescript. But in an ideal world, this would magically work

**Comment by erichonkanen** [comment]
ok cool gotcha.. so verdict is it'd be nice but probably won't happen? :D
