### ISSUE TITLE
Breaks ember-cli-rails exclude_ember_deps option

### ISSUE THREAD

**Issue by botandrose** [alexspeller/ember-cli-coffees6#14]
When using this library in conjunction with rwz/ember-cli-rails the latter's `exclude_ember_deps` option no longer has any effect. Can't tell exactly why yet, but my first guess is that they both munge `legacyFilesToAppend`. Going to dig into this further, but I'd appreciate any insight.

**Comment by alexspeller** [comment]
Can't reproduce this issue, please reopen if it's still an issue. I don't touch `legacyFilesToAppend`, ember-cli-coffees6 is just a relatively simple preprocessor
