### ISSUE TITLE
ember-cli 0.2.0: Could not find module appname/app

### ISSUE THREAD

**Issue by devinrhode2** [alexspeller/ember-cli-coffees6#9]
After upgrading to ember-cli 0.2.0 I got the error `Could not find module appname/app` with my app here: https://github.com/devinrhode2/major-domo/tree/95cfed62b88c29f07c5f4f7ef1580f43d668f390

Because this module was using the latest `ember-cli-coffeescript` when the error occurred, I had raised the issue there first: https://github.com/kimroen/ember-cli-coffeescript/issues/70 but after switching all import/exports to escaped js, and swapping the modules, thing bug went away. This means that the bug lies within `coffees6` and/or how it invokes `ember-cli-coffeescript`.

But, switching just app.coffee to the default ember-init generated app.js fixes the issue. router.coffee has no issues and doesn't need to be touched. Therefore, coffees6 actually does work with ember-cli 0.2.0, if app.coffee is converted to app.js. (Also, escaping the import/exports in app.coffee doesn't sold the issue, with or without semicolons, it needs to be fully converted to javascript)

So, I'm just going to keep doing everything normally but with an app.js instead of an app.coffee. 

And to be clear, `cat node_modules/ember-cli-coffees6/node_modules/ember-cli-coffeescript/package.json` shows coffees6 is using v0.10.0 of `ember-cli-coffeescript`.

I'm extremely certain of these statements which you can verify yourself, and I hope this saves you debugging time! Since this module is already a hack, I think forcing users to do an app.js instead of app.coffee is more than acceptable, and we should instead focus efforts on making a more elegant solution to using import/exports in coffeescript.

**Comment by alexspeller** [comment]
This should be fixed now
